/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as _rootIndexRouteImport } from './routes/__root/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'

const DashboardAnggotaLazyRouteImport = createFileRoute('/dashboard/anggota')()
const DashboardAdminLazyRouteImport = createFileRoute('/dashboard/admin')()

const _rootIndexRoute = _rootIndexRouteImport.update({
  id: '/__root/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnggotaLazyRoute = DashboardAnggotaLazyRouteImport.update({
  id: '/anggota',
  path: '/anggota',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/anggota.lazy').then((d) => d.Route),
)
const DashboardAdminLazyRoute = DashboardAdminLazyRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/admin.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminLazyRoute
  '/dashboard/anggota': typeof DashboardAnggotaLazyRoute
  '/': typeof _rootIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminLazyRoute
  '/dashboard/anggota': typeof DashboardAnggotaLazyRoute
  '/': typeof _rootIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminLazyRoute
  '/dashboard/anggota': typeof DashboardAnggotaLazyRoute
  '/__root/': typeof _rootIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/anggota'
    | '/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contact'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/anggota'
    | '/'
    | '/dashboard'
  id:
    | '__root__'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/anggota'
    | '/__root/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  _rootIndexRoute: typeof _rootIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__root/': {
      id: '/__root/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _rootIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/anggota': {
      id: '/dashboard/anggota'
      path: '/anggota'
      fullPath: '/dashboard/anggota'
      preLoaderRoute: typeof DashboardAnggotaLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminLazyRoute: typeof DashboardAdminLazyRoute
  DashboardAnggotaLazyRoute: typeof DashboardAnggotaLazyRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminLazyRoute: DashboardAdminLazyRoute,
  DashboardAnggotaLazyRoute: DashboardAnggotaLazyRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  _rootIndexRoute: _rootIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
