/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as _rootIndexRouteImport } from './routes/__root/index'
import { Route as LoginRouteImport } from './routes/login'

const _rootAnggotaLazyRouteImport = createFileRoute('/__root/anggota')()
const _rootAdminLazyRouteImport = createFileRoute('/__root/admin')()

const _rootIndexRoute = _rootIndexRouteImport.update({
  id: '/__root/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const _rootAnggotaLazyRoute = _rootAnggotaLazyRouteImport
  .update({
    id: '/__root/anggota',
    path: '/anggota',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/__root/anggota.lazy').then((d) => d.Route))
const _rootAdminLazyRoute = _rootAdminLazyRouteImport
  .update({
    id: '/__root/admin',
    path: '/admin',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/__root/admin.lazy').then((d) => d.Route))
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/admin': typeof _rootAdminLazyRoute
  '/anggota': typeof _rootAnggotaLazyRoute
  '/': typeof _rootIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof _rootAdminLazyRoute
  '/anggota': typeof _rootAnggotaLazyRoute
  '/': typeof _rootIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/__root/admin': typeof _rootAdminLazyRoute
  '/__root/anggota': typeof _rootAnggotaLazyRoute
  '/__root/': typeof _rootIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/admin' | '/anggota' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/admin' | '/anggota' | '/'
  id: '__root__' | '/login' | '/__root/admin' | '/__root/anggota' | '/__root/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  _rootAdminLazyRoute: typeof _rootAdminLazyRoute
  _rootAnggotaLazyRoute: typeof _rootAnggotaLazyRoute
  _rootIndexRoute: typeof _rootIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__root/': {
      id: '/__root/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _rootIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__root/anggota': {
      id: '/__root/anggota'
      path: '/anggota'
      fullPath: '/anggota'
      preLoaderRoute: typeof _rootAnggotaLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__root/admin': {
      id: '/__root/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof _rootAdminLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  _rootAdminLazyRoute: _rootAdminLazyRoute,
  _rootAnggotaLazyRoute: _rootAnggotaLazyRoute,
  _rootIndexRoute: _rootIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
